### ISSUE TITLE
check

### ISSUE THREAD

**Issue by MP5s** [popvictor123/YaProject#1]
Привет, при проверке твоего кода возникли некоторые проблемы:
### Некритические:

> Код запускается(не по инструкции) через go run ./cmd/project/...

 
Хорошо бы исправить.

> Ну и было бы хорошо, если бы ты добавил тесты(один из критериев)

 ### Баги:
![bug](https://github.com/user-attachments/assets/e645015b-a099-4d30-8870-14f559c89937)

> Не отображает код ошибки.

![bug2](https://github.com/user-attachments/assets/645e374c-34ee-4902-935a-4f3b6952a17f)

> Бесконечность, вместо ошибки

![bug3](https://github.com/user-attachments/assets/4f4370b5-97a8-4969-b631-e8b2b4cd3665)

> Также не отображает код ошибки

**Comment by popvictor123** [comment]
Привет, пофиксил.
